export const categories = [
  "cardio",
  "chest",
  "lower arms",
  "lower legs",
  "back",
  "neck",
  "shoulders",
  "upper arms",
  "upper legs",
  "waist",
];

export const exerciseData = {
  bodyPart: "waist",
  equipment: "body weight",
  gifUrl: "https://edb-4rme8.ondigitalocean.app/image/uWuJH4FzcCoakH",
  id: "0001",
  name: "3/4 sit-up",
  target: "abs",
};

export const resData = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/uWuJH4FzcCoakH",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/0FzcgxUIhTGNO1",
    id: "0002",
    name: "45° side bend",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/Z8QJWoPmCiLmNR",
    id: "0003",
    name: "air bike",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/-MTBYlV9EIN-mZ",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/PJqbuDOKSGA9rb",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/77jwcpaT6dNP4k",
    id: "2333",
    name: "arm slingers hanging straight legs",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/IT49BWXUvGEbA3",
    id: "3204",
    name: "arms overhead full sit-up (male)",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/zN4vp0Fvu4rttT",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/T5n3Sie-VEjKb9",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/gCtYYdWEeh9tTI",
    id: "0012",
    name: "assisted lying leg raise with lateral throw down",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/pbw9PJpyPTA0XS",
    id: "0013",
    name: "assisted lying leg raise with throw down",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "medicine ball",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/ZRMgiroCawsNCC",
    id: "0014",
    name: "assisted motion russian twist",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/B5JYgRIpU60Mf2",
    id: "1714",
    name: "assisted prone rectus femoris stretch",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/IZAGrVvcs853n1",
    id: "1758",
    name: "assisted sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/7r-4JK6j5nCOX5",
    id: "0969",
    name: "band alternating v-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/p9rD2PT8p6vKLl",
    id: "0971",
    name: "band assisted wheel rollerout",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/7B3PiL-lCb5BAk",
    id: "0972",
    name: "band bicycle crunch",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/EfiCl8NkWBehSh",
    id: "0979",
    name: "band horizontal pallof press",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/FCojecxMt4tMhn",
    id: "0981",
    name: "band jack knife sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/2vQiY42c9w7hq1",
    id: "0985",
    name: "band kneeling twisting crunch",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/oWMC7y4omHETJM",
    id: "1002",
    name: "band lying straight leg raise",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/69iU9LkccPRHOa",
    id: "0992",
    name: "band push sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/40Z64kwmqEFW5A",
    id: "1011",
    name: "band seated twist",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/4GexpzeNhB3-qs",
    id: "1005",
    name: "band standing crunch",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/KMZfLtv7OMyccH",
    id: "1007",
    name: "band standing twisting crunch",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/CDFccP6LpGuha3",
    id: "1014",
    name: "band v-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/lq-eSB4OtMa4Kd",
    id: "1015",
    name: "band vertical pallof press",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/jyeO1PzD50xJ8c",
    id: "0071",
    name: "barbell press sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/-sMHHImASQOcpd",
    id: "0084",
    name: "barbell rollerout",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/sV3ptepKJSQ3ax",
    id: "0083",
    name: "barbell rollerout from bench",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/9299xz-cmxIqCO",
    id: "0094",
    name: "barbell seated twist",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/H2gvHnuXPm1SSB",
    id: "0096",
    name: "barbell side bent v. 2",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/O0QSqt8lIHbvKL",
    id: "2799",
    name: "barbell sitted alternate leg raise",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/r8AA8y-8FEB3WL",
    id: "2800",
    name: "barbell sitted alternate leg raise (female)",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/b5Acb8ApdLfW3d",
    id: "0103",
    name: "barbell standing ab rollerout",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/qw8rEH4TCYF9Tx",
    id: "0112",
    name: "barbell standing twist",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/XCtx-Hlerbcnr1",
    id: "0858",
    name: "wind sprints",
    target: "abs",
  },
];
